spring.application.name=HealthCare
#spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_db
#spring.datasource.url=jdbc:postgresql://localhost:5432/healthcare_db
spring.datasource.url=jdbc:postgresql://healthstationdb.cdcg4y6q0akb.eu-north-1.rds.amazonaws.com:5432/healthmanagement
spring.datasource.username=postgres
spring.datasource.password=HealthStation

# Optional but recommended settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect